name = "screen-recorder-api"
main = "src/worker.js"
compatibility_date = "2024-09-16"

# Enable Workers KV for storing recordings metadata if needed
# [[kv_namespaces]]
# binding = "RECORDINGS"
# id = "your-kv-namespace-id"
# preview_id = "your-preview-kv-namespace-id"

# Environment variables
[env.production]
vars = { ENVIRONMENT = "production" }

[env.staging]
vars = { ENVIRONMENT = "staging" }

# Configure R2 bucket for file storage
[[r2_buckets]]
binding = "RECORDINGS_BUCKET"
bucket_name = "screen-recorder-files"